### ISSUE TITLE
Breaking changes in 0.2.1

### ISSUE THREAD

**Issue by RazrFalcon** [gtk-rs/pangocairo#3]
```
error[E0432]: unresolved import `pangocairo::CairoContextExt`
error[E0432]: unresolved import `pangocairo::PangoContextExt`
error[E0599]: no method named `create_pango_context` found for type `&cairo::Context` in the current scope
error[E0599]: no method named `update_pango_context` found for type `&cairo::Context` in the current scope
error[E0599]: no method named `update_pango_layout` found for type `&cairo::Context` in the current scope
error[E0599]: no method named `show_pango_layout` found for type `&cairo::Context` in the current scope
error[E0599]: no method named `pango_layout_path` found for type `&cairo::Context` in the current scope
```

**Comment by GuillaumeGomez** [comment]
Is it from renaming or missing types? (I should have change the medium version number...)

**Comment by RazrFalcon** [comment]
From missing traits, I guess. And I can't find alternatives to the old methods.

**Comment by RazrFalcon** [comment]
Is this repo has no code at all? All it do is reexport unsafe ffi methods. Am I missing something?

**Comment by GuillaumeGomez** [comment]
It has very few methods, indeed. I think we'll need to manually add what's missing because the automatic generation is missing a lot of things. Do you still have your code? A big PR to add what's missing would be appreciated. :)

**Comment by RazrFalcon** [comment]
I'm busy at the moment, but all the code is here: https://github.com/RazrFalcon/pangocairo-rs/blob/master/src/lib.rs

0.2.1 should be yanked.

**Comment by RazrFalcon** [comment]
`pangocairo-sys` also should be yanked, because `pangocairo` failed to build with `pangocairo-sys=0.4.1`.

**Comment by GuillaumeGomez** [comment]
Ah right, good point.

**Comment by RazrFalcon** [comment]
I've yanked `pangocairo-sys` by myself, because it broke my build.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by GuillaumeGomez** [comment]
I pushed a `0.3.0` version instead (and a `0.5.0` for `pangocairo-sys`) so this shouldn't be an issue anymore. Sorry for the inconvenience!

**Comment by RazrFalcon** [comment]
So there are still breaking changes and no traits like in `0.2`?

**Comment by GuillaumeGomez** [comment]
No. It's... strange.

**Comment by RazrFalcon** [comment]
Any plans to add old traits?

I can make a pull request.

**Comment by GuillaumeGomez** [comment]
No but if you want them, any PR is welcome.
